# Generated by Django 2.2.5 on 2021-02-04 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='school',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(blank=True, max_length=10, null=True)),
                ('School_address', models.CharField(max_length=10, unique=True)),
                ('school_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('school_id', models.CharField(blank=True, max_length=10, null=True)),
                ('school_img', models.FileField(blank=True, null=True, upload_to='media/img')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=10, null=True)),
                ('student_id', models.CharField(blank=True, max_length=10, null=True)),
                ('student_class', models.CharField(blank=True, max_length=10, null=True)),
                ('student_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('student_email', models.CharField(blank=True, max_length=10, null=True)),
                ('student_info', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(blank=True, max_length=10, null=True)),
                ('teacher_id', models.CharField(blank=True, max_length=10, null=True)),
                ('teacher_email', models.CharField(blank=True, max_length=10, null=True)),
                ('teacher_info', models.CharField(blank=True, max_length=10, null=True)),
                ('teacher_mobile', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=10, unique=True)),
                ('subject_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('subject_teacher_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stu.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='class_t',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_t_name', models.CharField(blank=True, max_length=10, null=True)),
                ('class_t_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True, null=True)),
                ('updatedAt', models.DateTimeField(auto_now=True, null=True)),
                ('class_t_subject', models.ManyToManyField(to='stu.subject')),
                ('class_t_teacher', models.ManyToManyField(to='stu.teacher')),
                ('class_t_tutor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
