# Generated by Django 2.2.5 on 2021-02-05 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stu', '0002_school_school_which_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='School_address',
        ),
    ]
